baseURL = 'https://balmabrian.github.io'
languageCode = 'en-us'
theme = "hugo-theme-monochrome"
title = "The Dev Corner"

[params]
  footer = "Made by Brian Almaguer"
  enable_toc = false

[menu]
  [[menu.navbar]]
    name = "Home"
    url = "/"
    weight = 1
# 
  [[menu.navbar]]
    name = "About"
    url = "/about/"
    weight = 2
# 
  [[menu.navbar]]
    name = "Posts"
    url = "/posts/"
    weight = 3
# 
  [[menu.navbar]]
    name = "Notes"
    url = "/notes/"
    weight = 4
# 
  [[menu.navbar]]
    name = "Work"
    url = "/work/"
    weight = 5