baseURL = 'https://balmabrian.github.io/'
languageCode = 'en-us'
title = "The Dev Corner"
theme = 'researcher'
  
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 3

[[menu.main]]
  name = "Notes"
  url = "/notes/"
  weight = 4

[[menu.main]]
  name = "Work"
  url = "/work/"
  weight = 5