baseURL = 'https://balmabrian.github.io'
languageCode = 'en-us'
title = "The Dev Corner"
theme = ""

[params]
  author = "Brian Almaguer"
  description = "A blog about software development and other things."
  # favicon = "favicon.ico"  # path to a .ico to use as favicon
  # logo = ""  # url or path to a logo to put in the header
  [params.footer]
    text = "By Brian Almaguer"
    url = "https://github.com/balmabrian"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 3

  [[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 4

  [[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 5

[markup.goldmark.renderer]
  unsafe = true