baseURL = 'https://balmabrian.github.io/'
languageCode = 'en-us'
title = "BalmaBrian's Development Site"
theme = 'hugo-xmin'

# [params]
  # footer = "&copy; [Yihui Xie](https://yihui.name) 2017"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 3

[[menu.main]]
  name = "Notes"
  url = "/notes/"
  weight = 4

[[menu.main]]
  name = "Work/Research"
  url = "/work/"
  weight = 5

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 6